openapi: 3.1.0
info:
  title: Workout Tracker API
  description: API for tracking workouts, exercises, and generating reports
  version: 1.0.0

servers:
  - url: http://localhost:3000
    description: Development server

components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT

  schemas:
    User:
      type: object
      properties:
        id:
          type: string
          format: uuid
        email:
          type: string
          format: email
        createdAt:
          type: string
          format: date-time
        workouts:
          type: array
          items:
            $ref: '#/components/schemas/Workout'

    Exercise:
      type: object
      properties:
        id:
          type: string
          format: uuid
        name:
          type: string
        description:
          type: string
        category:
          type: string
          enum: [cardio, strength, flexibility]
        muscleGroup:
          type: string
        workouts:
          type: array
          items:
            $ref: '#/components/schemas/WorkoutExercise'

    Workout:
      type: object
      properties:
        id:
          type: string
          format: uuid
        title:
          type: string
        notes:
          type: string
        scheduledAt:
          type: string
          format: date-time
        user:
          $ref: '#/components/schemas/User'
        userId:
          type: string
          format: uuid
        exercises:
          type: array
          items:
            $ref: '#/components/schemas/WorkoutExercise'
        createdAt:
          type: string
          format: date-time

    WorkoutExercise:
      type: object
      properties:
        id:
          type: string
          format: uuid
        workout:
          $ref: '#/components/schemas/Workout'
        workoutId:
          type: string
          format: uuid
        exercise:
          $ref: '#/components/schemas/Exercise'
        exerciseId:
          type: string
          format: uuid
        sets:
          type: integer
        reps:
          type: integer
        weight:
          type: integer

paths:
  /health:
    get:
      summary: Health check endpoint
      responses:
        '200':
          description: API is running
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: string
                  message:
                    type: string

  /auth/signup:
    post:
      summary: Register a new user
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required:
                - email
                - password
              properties:
                email:
                  type: string
                  format: email
                password:
                  type: string
      responses:
        '201':
          description: User created successfully
        '400':
          description: Invalid input

  /auth/login:
    post:
      summary: Login user
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required:
                - email
                - password
              properties:
                email:
                  type: string
                  format: email
                password:
                  type: string
      responses:
        '200':
          description: Login successful
          content:
            application/json:
              schema:
                type: object
                properties:
                  token:
                    type: string
        '401':
          description: Invalid credentials

  /workouts:
    get:
      summary: Get all workouts for authenticated user
      security:
        - bearerAuth: []
      responses:
        '200':
          description: List of workouts
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Workout'
        '401':
          description: Unauthorized

    post:
      summary: Create a new workout
      security:
        - bearerAuth: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Workout'
      responses:
        '201':
          description: Workout created successfully
        '401':
          description: Unauthorized

  /workouts/scheduled:
    get:
      summary: Get scheduled workouts
      security:
        - bearerAuth: []
      responses:
        '200':
          description: List of scheduled workouts
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Workout'
        '401':
          description: Unauthorized

  /workouts/{id}:
    parameters:
      - name: id
        in: path
        required: true
        schema:
          type: string
          format: uuid
    get:
      summary: Get workout by ID
      security:
        - bearerAuth: []
      responses:
        '200':
          description: Workout details
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Workout'
        '401':
          description: Unauthorized
        '404':
          description: Workout not found

    put:
      summary: Update workout
      security:
        - bearerAuth: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Workout'
      responses:
        '200':
          description: Workout updated successfully
        '401':
          description: Unauthorized
        '404':
          description: Workout not found

    delete:
      summary: Delete workout
      security:
        - bearerAuth: []
      responses:
        '204':
          description: Workout deleted successfully
        '401':
          description: Unauthorized
        '404':
          description: Workout not found

  /exercises:
    get:
      summary: Get all exercises
      responses:
        '200':
          description: List of exercises
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Exercise'

  /reports:
    get:
      summary: Generate workout report
      security:
        - bearerAuth: []
      responses:
        '200':
          description: Workout report generated successfully
        '401':
          description: Unauthorized 